services:
  mysql:
    image: elestio/mysql:8.0
    restart: always
    hostname: mysql
    volumes:
      - ./storage/mysql:/var/lib/mysql
    ports:
      - "172.17.0.1:50778:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  glpi:
    image: elestio/glpi:${SOFTWARE_VERSION_TAG}
    restart: always
    hostname: glpi
    ports:
      - "172.17.0.1:22571:80"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./storage/var/www/html/glpi/:/var/www/html/glpi
      - ./apache/php.ini:/etc/php/8.1/apache2/php.ini
    environment:
      - TIMEZONE=America/Asuncion
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - DOMAIN=${DOMAIN}

  pma:
    image: phpmyadmin
    restart: always
    links:
      - mysql:mysql
    ports:
      - "172.17.0.1:22811:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=${ADMIN_PASSWORD}
      - UPLOAD_LIMIT=500M
      - MYSQL_USERNAME=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD=${ADMIN_PASSWORD}
    depends_on:
      - mysql
