#version: '3'

services:
  mysql:
    image: elestio/mysql:8.0
    restart: always
    hostname: mysql
    volumes:
      - ./storage/mysql:/var/lib/mysql
    ports:
      - "50778:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  glpi:
    image: elestio/glpi:${SOFTWARE_VERSION_TAG}
    restart: always
    hostname: glpi
    ports:
      - "22571:80"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./storage/var/www/html/glpi/:/var/www/html/glpi
      - ./php/custom.ini:/etc/php/8.1/cli/conf.d/custom.ini
      #- ./php/session.cookie_httponly.ini:/etc/php/8.1/cli/conf.d/session.cookie_httponly.ini
    environment:
      - TIMEZONE=America/Asuncion
      #- ADMIN_EMAIL=${ADMIN_EMAIL}
      #- DOMAIN=${DOMAIN}

  pma:
    image: phpmyadmin
    restart: always
    links:
      - mysql:mysql
    ports:
      - "22811:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}  # Usa MYSQL_ROOT_PASSWORD
      - UPLOAD_LIMIT=500M
      - MYSQL_USERNAME=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}  # Usa MYSQL_ROOT_PASSWORD
    depends_on:
      - mysql
